### ISSUE TITLE
Нарушение принципов ООП

### ISSUE THREAD

**Issue by dnsonin** [ncedu-tlt/2018-dimi1-expense-manager#5]
Привет,

Я нашел 2 случая, где методы классов реализованы и используются с нарушением принципов ООП. Такой код трудно понять не заглядывая в имплементацию, хотя программа работает правильно.

1) 
https://github.com/ncedu-tlt/2018-dimi1-expense-manager/blob/88790c07f2d0198a2d0ffe17f1de7f4c17cb61df/src/main/java/orlova/Main.java#L515-L518

Здесь код читается как:
Создать объект, присвоить ему ID и сразу же удалить. Зачем создавали? Зачем время тратили?

Мне понятно, зачем здесь .setBudgetId(), потому что для .delete() нужно чтобы у объекта был не пустой budgetId. Но такой код заставляет тратить больше времени, чтобы понять алгоритм.
Вместо .setBudgetId() я бы предложил использовать .load(id) (который поднимает все поля с базы, включая id) - тогда будет понятно, что мы удаляем объект, который уже лежит в базе. Да, это спровоцирует дополнительный SELECT, но это уже вопрос к архитектуре.

2)
https://github.com/ncedu-tlt/2018-dimi1-expense-manager/blob/88790c07f2d0198a2d0ffe17f1de7f4c17cb61df/src/main/java/orlova/Main.java#L528-L530

Здесь с первого взгляда не понятно что представляет из себя объект objPersForUpdate. Сначала он используется для проверки наличия юзера по id, затем он вроде как сам становится этим юзером ( используя .load(id) ) , и после того как мы ему достали данные из БД, зачем-то еще раз ему присваивается id ( .setPersonId() ).

Я бы предложил реорганизовать подобные конструкции. Для проверки удалось ли поднять пользователя из БД - я бы предложил сделать метод .load() возвращающим boolean значение, а ещё лучше - бросать исключение с ошибкой, что пользователя с этим id не существует. Опять же .load(id) должен включать в себя присвоение id внутри метода.

**Comment by dnsonin** [comment]
Привет Полина,

С методом .load(id), на мой взгляд - код стал логичнее.

Использование методов ".is{smth}Exist(id)" можно было бы избежать, используя .load(id),
но я вижу, что принцип ты поняла.

Тикет закрываю.

Спасибо.

**Comment by torichay** [comment]
Здравствуйте, Денис.
Спасибо, что приняли мои изменения, единственное, хочу пояснить, что я намеренно оставила методы is...Exists. В тех моментах, в которых я его использую, я посчитала, что ни к чему гонять по трафику те данные, которые тянет за собой метод load, а достаточно будет работы метода is...Exists, возвращающего из базы одно значение COUNT(*).


>Пятница, 15 февраля 2019, 14:23 +04:00 от Denis Sonin <notifications@github.com>:
>
>Привет Полина,
>С методом .load(id), на мой взгляд - код стал логичнее.
>Использование методов ".is{smth}Exist(id)" можно было бы избежать, используя .load(id),
>но я вижу, что принцип ты поняла.
>Тикет закрываю.
>Спасибо.
>—
>You are receiving this because you were assigned.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
С уважением, Полина Орлова
Сот. тел.: 89171230859

**Comment by dnsonin** [comment]
> Здравствуйте, Денис. Спасибо, что приняли мои изменения, единственное, хочу пояснить, что я намеренно оставила методы is...Exists. В тех моментах, в которых я его использую, я посчитала, что ни к чему гонять по трафику те данные, которые тянет за собой метод load, а достаточно будет работы метода is...Exists, возвращающего из базы одно значение COUNT(*).
> […](#)
> Пятница, 15 февраля 2019, 14:23 +04:00 от Denis Sonin ***@***.***>: Привет Полина, С методом .load(id), на мой взгляд - код стал логичнее. Использование методов ".is{smth}Exist(id)" можно было бы избежать, используя .load(id), но я вижу, что принцип ты поняла. Тикет закрываю. Спасибо. — You are receiving this because you were assigned. Reply to this email directly, view it on GitHub , or mute the thread .
> -- С уважением, Полина Орлова Сот. тел.: 89171230859

Правильно, что задумываешься, о нагрузке на трафик, но оптимальность кода хорошо бы сочетать с читаемостью. 
Если у тебя есть желание и время - я могу завести ещё один тикет и попробуем улучшить наш код :)
